#!/bin/bash
curl -s --user $1:$2 --cookie-jar ./cookie http://172.31.1.200/pas/login >out
curl -s --cookie ./cookie http://172.31.1.200/pas/student > page
#notice=`python gen.py`
#echo $notice
#notify-send $notice

python gen.py > out
notify-send "Updates" "$(cat ./out)"
rm out

